version: 0.0
os: linux
# During the Install deployment lifecycle event (which occurs between the
#   BeforeInstall and AfterInstall events), copy the specified files
#   in "source" starting from the root of the revision's file bundle
#   to "destination" on the instance.
# Specify multiple "source" and "destination" pairs if you want to copy
#   from multiple sources or to multiple destinations.
# If you are not copying any files to the instance, then remove the
#   "files" section altogether. A blank or incomplete "files" section
#   may cause associated deployments to fail.
files:
  - source: /
    destination: /home/ubuntu/sorta-server
hooks:
  # During the AfterInstall deployment lifecycle event, run the commands
  #   in the script specified in "location".
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu
  # During the ApplicationInstall deployment lifecycle event, run the commands
  #   in the script specified in "location".
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu
